export const wasteItems = [
  {
    id: 1,
    name: 'Plastic Bottle',
    category: 'plastics',
    icon: '🍾',
    image: 'https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=400',
    contamination: false,
    preparation: ['Remove cap and label', 'Rinse thoroughly', 'Crush to save space'],
    upcyclingTip: 'Cut in half and use as a planter, bird feeder, or pencil holder',
    barcode: '5449000000996',
  },
  {
    id: 2,
    name: 'Food Scraps',
    category: 'bio',
    icon: '🍎',
    image: 'https://images.unsplash.com/photo-1610832958506-aa56368176cf?w=400',
    contamination: false,
    preparation: ['Remove non-organic materials', 'No meat or dairy in some regions', 'Drain excess liquid'],
    upcyclingTip: 'Create compost for your garden. Mix with dry leaves and turn weekly.',
    barcode: null,
  },
  {
    id: 3,
    name: 'Aluminum Can',
    category: 'plastics',
    icon: '🥫',
    image: 'https://images.unsplash.com/photo-1559080074-5d3b6d87106f?w=400',
    contamination: false,
    preparation: ['Rinse inside', 'Crush if possible', 'Remove any paper labels'],
    upcyclingTip: 'Use as small planters, pen holders, or candle holders after cleaning',
    barcode: '012000161551',
  },
  {
    id: 4,
    name: 'Glass Jar',
    category: 'glass',
    icon: '🫙',
    image: 'https://images.unsplash.com/photo-1524678714210-9917a6c619c2?w=400',
    contamination: false,
    preparation: ['Remove lid', 'Rinse clean', 'Separate by color if required'],
    upcyclingTip: 'Perfect for food storage, DIY terrariums, or organizing small items',
    barcode: null,
  },
  {
    id: 5,
    name: 'Newspaper',
    category: 'paper',
    icon: '📰',
    image: 'https://images.unsplash.com/photo-1504711434969-e33886168f5c?w=400',
    contamination: false,
    preparation: ['Keep dry', 'Remove plastic wrapping', 'Stack neatly'],
    upcyclingTip: 'Use for wrapping gifts, cleaning windows, or as mulch for gardening',
    barcode: null,
  },
  {
    id: 6,
    name: 'Old Battery',
    category: 'ewaste',
    icon: '🔋',
    image: 'https://images.unsplash.com/photo-1609091839311-d7f4b5d82e59?w=400',
    contamination: true,
    preparation: ['Do NOT throw in regular bins', 'Store in cool, dry place', 'Tape terminals of lithium batteries'],
    upcyclingTip: 'Take to designated e-waste collection centers. Never dispose with regular trash.',
    barcode: null,
  },
  {
    id: 7,
    name: 'Cardboard Box',
    category: 'paper',
    icon: '📦',
    image: 'https://images.unsplash.com/photo-1566933293069-b55c7f326dd4?w=400',
    contamination: false,
    preparation: ['Flatten the box', 'Remove tape and staples', 'Keep dry and clean'],
    upcyclingTip: 'Use for DIY storage boxes, cat houses, or children\'s craft projects',
    barcode: null,
  },
  {
    id: 8,
    name: 'Orange Peel',
    category: 'bio',
    icon: '🍊',
    image: 'https://images.unsplash.com/photo-1580052614034-c55d20bfee3b?w=400',
    contamination: false,
    preparation: ['No processing needed for composting'],
    upcyclingTip: 'Dry for 7 days → crush into powder → mix with soil as natural fertilizer and pest repellent',
    barcode: null,
  },
];

export const categories = [
  { id: 'plastics', name: 'Plastics & Packaging', icon: '♻️', description: 'PET bottles, HDPE containers, film plastic' },
  { id: 'paper', name: 'Paper & Cardboard', icon: '📄', description: 'Newspapers, cardboard, office paper' },
  { id: 'glass', name: 'Glass', icon: '🫙', description: 'Bottles and jars (clear, brown, green)' },
  { id: 'bio', name: 'Bio/Organic', icon: '🍎', description: 'Food scraps, garden waste, compostables' },
  { id: 'residual', name: 'Residual Waste', icon: '🗑️', description: 'Non-recyclable items' },
  { id: 'ewaste', name: 'E-Waste', icon: '🔋', description: 'Electronics, batteries, hazardous materials' },
];

export const upcyclingIdeas = [
  {
    id: 1,
    title: 'Plastic Bottle Planter',
    item: 'Plastic Bottle',
    difficulty: 'Easy',
    duration: '15 minutes',
    materials: ['Plastic bottle', 'Scissors', 'Soil', 'Seeds'],
    steps: [
      'Cut the bottle in half horizontally',
      'Poke drainage holes in the bottom',
      'Fill with potting soil',
      'Plant your favorite herbs or flowers',
      'Decorate with paint or markers'
    ],
    image: 'https://images.unsplash.com/photo-1466692476868-aef1dfb1e735?w=400',
  },
  {
    id: 2,
    title: 'Orange Peel Fertilizer',
    item: 'Orange Peel',
    difficulty: 'Easy',
    duration: '7 days + 10 minutes',
    materials: ['Orange peels', 'Sunlight', 'Mortar & pestle or blender'],
    steps: [
      'Collect orange peels after eating',
      'Dry in sunlight for 7 days until crispy',
      'Crush into fine powder',
      'Mix 2 tablespoons with garden soil',
      'Acts as natural fertilizer and pest repellent'
    ],
    image: 'https://images.unsplash.com/photo-1580052614034-c55d20bfee3b?w=400',
  },
  {
    id: 3,
    title: 'Glass Jar Storage',
    item: 'Glass Jar',
    difficulty: 'Easy',
    duration: '5 minutes',
    materials: ['Clean glass jar', 'Labels (optional)', 'Paint (optional)'],
    steps: [
      'Remove all labels and clean thoroughly',
      'Dry completely',
      'Use for pantry storage (rice, pasta, spices)',
      'Or create a DIY terrarium with soil and succulents',
      'Paint lids for color coordination'
    ],
    image: 'https://images.unsplash.com/photo-1524678714210-9917a6c619c2?w=400',
  },
];
